version: '3.9'

services:
  delete-data:
    image: node:18-alpine
    networks:
      hapi-fhir:
      elastic:
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - "node.labels.name==node-1"
    command: sh -c "cd /app && npm run 1:delete"
    volumes:
      - ../:/app
    environment:
      OUTPUT_PATH: './output'
      FACILITY_ID: 'placeholder'
      ELASTIC_URL: 'http://elasticsearch_analytics-datastore-elastic-search-01:9200'
      ELASTIC_PASSWORD: 'dev_password_only'
      HAPI_FHIR_URL: 'hapi-fhir'
      HAPI_FHIR_PORT: 8080

networks:
  hapi-fhir:
    name: hapi-fhir_public
    external: true
  elastic:
    name: elastic_public
    external: true
