version: '3.9'

services:
  delete-data:
    image: node:18-alpine
    networks:
      openhim:
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - "node.labels.name==node-1"
    command: sh -c "cd /app && npm run 2:deleter"
    volumes:
      - ../:/app
    environment:
      FACILITY_ID: 'placeholder'
      ELASTIC_URL: 'http://elasticsearch_analytics-datastore-elastic-search-01:9200'
      ELASTIC_PASSWORD: 'dev_password_only'
      HAPI_FHIR_URL: 'hapi-fhir'
      HAPI_FHIR_PORT: 8080

networks:
  openhim:
    name: openhim_public
    external: true
